name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            suffix: ""
          - goos: linux
            goarch: arm64
            suffix: ""
          - goos: darwin
            goarch: amd64
            suffix: ""
          - goos: darwin
            goarch: arm64
            suffix: ""
          - goos: windows
            goarch: amd64
            suffix: ".exe"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Extract version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Update version.txt
        run: echo "${{ steps.get_version.outputs.VERSION }}" > version.txt

      - name: Build
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          mkdir -p dist
          go build -ldflags "-X github.com/naotama2002/dalv/internal/version.Version=${{ steps.get_version.outputs.VERSION }}" -o dist/dalv${{ matrix.suffix }} ./cmd/dalv

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dalv-${{ matrix.goos }}-${{ matrix.goarch }}
          path: dist/dalv${{ matrix.suffix }}
          retention-days: 7

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Prepare assets
        run: |
          mkdir -p release
          cp artifacts/dalv-linux-amd64/dalv release/dalv-linux-amd64
          cp artifacts/dalv-linux-arm64/dalv release/dalv-linux-arm64
          cp artifacts/dalv-darwin-amd64/dalv release/dalv-darwin-amd64
          cp artifacts/dalv-darwin-arm64/dalv release/dalv-darwin-arm64
          cp artifacts/dalv-windows-amd64/dalv.exe release/dalv-windows-amd64.exe
          
          cd release
          sha256sum * > checksums.txt
          cd ..

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/dalv-linux-amd64
            release/dalv-linux-arm64
            release/dalv-darwin-amd64
            release/dalv-darwin-arm64
            release/dalv-windows-amd64.exe
            release/checksums.txt
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
